-- EXECUTE THIS SCRIPT TO ADD ONLY THE MISSING TABLES
-- This will NOT affect your existing Students, Courses, or Grades tables.
-- RLS (Row Level Security) steps have been removed as requested.

-- 1. Hall Tickets (Needed for Exam Portal)
create table if not exists public.hall_tickets (
  id bigint generated by default as identity primary key,
  student_id text,
  exam_id bigint references public.exam_master(id),
  token text, -- The generated hall ticket string
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Transport Fares (Needed for Transport Portal)
-- You have transport_routes, but the code looks for a fares table too.
create table if not exists public.transport_route_fares (
  id bigint generated by default as identity primary key,
  route_id bigint references public.transport_routes(id) on delete cascade,
  academic_year text references public.academic_year(academic_year),
  amount numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Batches (Simple reference table used in some dropdowns)
create table if not exists public.batches (
  id bigint generated by default as identity primary key,
  name text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Fix Foreign Key names for Dashboard (Critical for the '404' error in MainDashboard)
-- The frontend code specifically asks for `students_group_id_fkey` and `fk_students_course`.
-- We need to ensure these exactly exist on your 'students' table.

-- Drop existing constraints if they have different names to avoid duplicates (safely)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'students_group_id_fkey') THEN
    ALTER TABLE public.students DROP CONSTRAINT students_group_id_fkey;
  END IF;
  
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_students_course') THEN
    ALTER TABLE public.students DROP CONSTRAINT fk_students_course;
  END IF;
END $$;

-- Re-add them with the EXACT names the frontend requires
ALTER TABLE public.students
  ADD CONSTRAINT students_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(group_id);

ALTER TABLE public.students
  ADD CONSTRAINT fk_students_course FOREIGN KEY (course_id) REFERENCES public.courses(course_id);
