-- INSTRUCTIONS:
-- 1. Copy this entire script.
-- 2. Go to your Supabase Project Dashboard -> SQL Editor.
-- 3. Paste this script and click "Run".
-- 4. Afterwards, refresh your application.

-- 1. Enable UUID (optional but good practice)
create extension if not exists "uuid-ossp";

-- 2. Define Tables

-- Academic Year
create table if not exists public.academic_year (
  id bigint generated by default as identity primary key,
  academic_year text not null,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Groups (e.g., MPC, BCom)
create table if not exists public.groups (
  group_id bigint generated by default as identity primary key,
  group_name text not null,
  group_code text not null,
  duration_years integer default 3,
  number_semesters integer default 6,
  category text, -- 'UG' or 'PG' etc
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Courses (e.g., BSc MPC, BCom Computers)
create table if not exists public.courses (
  course_id bigint generated by default as identity primary key,
  course_name text not null,
  course_code text not null,
  group_id bigint references public.groups(group_id),
  group_name text, -- De-normalized or used if no FK
  no_of_semesters integer,
  duration_years integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Subject Categories (e.g. Core, Elective, Language)
create table if not exists public.subject_category (
  category_id bigint generated by default as identity primary key,
  category_name text not null,
  credits integer default 0,
  subjects_name jsonb, -- Storing list of subject names as JSON array if needed
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Subjects
create table if not exists public.subjects (
  subject_id bigint generated by default as identity primary key,
  academic_year text,
  course_name text,
  semester_number integer,
  category_id bigint references public.subject_category(category_id),
  subject_code text,
  subject_name text,
  fees_categories text,
  amount numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Students
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  student_id text unique,
  hall_ticket_no text unique,
  full_name text,
  gender text,
  date_of_birth date,
  email text,
  phone_number text,
  address text,
  father_name text,
  mother_name text,
  nationality text,
  state text,
  religion text,
  caste text,
  sub_caste text,
  aadhar_number text,
  pincode text,
  photo_url text,
  cert_url text,
  
  -- Academic Info
  academic_year text,
  group_name text,
  course_name text, -- course code usually stored here in this app
  current_semester integer,
  status text default 'ACTIVE',
  
  -- Foreign Keys (optional but recommended if strictly relational)
  group_id bigint references public.groups(group_id),
  course_id bigint references public.courses(course_id),
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Teachers / Staff
create table if not exists public.teachers (
  id bigint generated by default as identity primary key,
  full_name text,
  email text,
  phone_number text,
  designation text,
  department text,
  joining_date date,
  status text default 'ACTIVE',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Fee Structure Definitions
create table if not exists public.fee_structure (
  id bigint generated by default as identity primary key,
  academic_year text,
  group_name text,
  course_name text,
  semester integer,
  fee_cat text, -- Payment Type
  amount numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Fee Categories (Types)
create table if not exists public.fee_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  fees jsonb, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Student Fee Payments
create table if not exists public.student_fee_payments (
  id bigint generated by default as identity primary key,
  student_id text, -- references students(student_id)
  payment_status text default 'pending',
  academic_fee_id bigint,
  amount numeric,
  method text,
  reference text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Applications (Admissions)
create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  application_no text unique,
  admission_year text,
  course_id text,
  group_id text,
  full_name text,
  gender text,
  date_of_birth date,
  father_name text,
  mother_name text,
  nationality text,
  state text,
  religion text,
  caste text,
  aadhar_number text,
  address text,
  pincode text,
  phone_number text,
  parent_no text,
  tenth_register_no text,
  tenth_percentage numeric,
  twelth_register_no text,
  twelth_percentage numeric,
  photo_url text,
  cert_url text,
  status text default 'DRAFT',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Application Documents
create table if not exists public.application_documents (
  id bigint generated by default as identity primary key,
  application_id bigint references public.applications(id) on delete cascade,
  document_type text,
  document_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Exams Master
create table if not exists public.exam_master (
  id bigint generated by default as identity primary key,
  exam_name text,
  date date,
  time text,
  venue text,
  result_status text default 'PENDING',
  results_published boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Exam Schedules
create table if not exists public.exam_schedule (
  schedule_id bigint generated by default as identity primary key,
  academic_year text,
  semester_number integer,
  group_code text,
  course_code text,
  subject_code text,
  exam_date date,
  exam_start_time time,
  exam_end_time time,
  category text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Hall Tickets
create table if not exists public.hall_tickets (
  id bigint generated by default as identity primary key,
  student_id text,
  exam_id bigint,
  token text, -- The hall ticket number/string
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Results
create table if not exists public.results (
  id bigint generated by default as identity primary key,
  student_id text,
  exam_id bigint,
  total text, -- or numeric
  grade text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Batches
create table if not exists public.batches (
  id bigint generated by default as identity primary key,
  name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Transport Routes
create table if not exists public.transport_routes (
  id bigint generated by default as identity primary key,
  route_no text unique,
  route_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Transport Boarding Points
create table if not exists public.transport_route_boarding_points (
  id bigint generated by default as identity primary key,
  route_id bigint references public.transport_routes(id) on delete cascade,
  name text,
  stop_order integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Transport Fares
create table if not exists public.transport_route_fares (
  id bigint generated by default as identity primary key,
  route_id bigint references public.transport_routes(id) on delete cascade,
  academic_year text,
  amount numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Transport Vehicles
create table if not exists public.transport_vehicles (
  vehicle_no text primary key,
  route_id bigint references public.transport_routes(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. ENABLE ROW LEVEL SECURITY (RLS) FOR ALL TABLES
-- This prevents '401 Unauthorized' errors by defaulting to restricted, 
-- but we will add open policies for this app.

do $$ 
declare 
  t record;
begin 
  for t in 
    select tablename from pg_tables where schemaname = 'public' 
  loop 
    execute format('alter table public.%I enable row level security;', t.tablename);
    -- Add a generic policy to allow everything (FOR DEVELOPMENT ONLY)
    -- Drop existing if any to avoid conflicts
    execute format('drop policy if exists "Allow All" on public.%I;', t.tablename);
    execute format('create policy "Allow All" on public.%I for all using (true) with check (true);', t.tablename);
  end loop; 
end $$;

-- 4. Fix specific Foreign Keys needed by MainDashboard.jsx
-- The dashboard code explicitly tries to join `groups` via `students_group_id_fkey` 
-- and `courses` via `fk_students_course`. We MUST name them exactly so.

alter table public.students drop constraint if exists students_group_id_fkey;
alter table public.students add constraint students_group_id_fkey 
  foreign key (group_id) references public.groups(group_id);

alter table public.students drop constraint if exists fk_students_course;
alter table public.students add constraint fk_students_course 
  foreign key (course_id) references public.courses(course_id);

